[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StipplePlotly = "ec984513-233d-481d-95b0-a3b58b97af2b"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
